"""
Django settings for ServerTest project.

Generated by 'django-admin startproject' using Django 3.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from alibabacloud_tea_openapi import models as open_api_models
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*l*(!7bd&0k3l=^f=@#hfsefqs*re9ztuaymd$p95#j8n!1o*m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'MyServer',
    'UserSession',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ServerTest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ServerTest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hps_dev',
        'USER': 'hps_admin',
        'PASSWORD': 'QINNAIDi@123456_',
        'HOST': 'rm-bp101n61fa3de6c2bvo.mysql.rds.aliyuncs.com',
        'PORT': 3306,
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
AUTH_USER_MODEL = 'MyServer.UserInfo'
STATIC_URL = '/static/'
CACHES = {
    "default": {
        "BACKEND": "django_mysql.cache.MySQLCache",
        "LOCATION": "my_cache_table", #TODO:这里要改成自己的数据库名
        # "OPTIONS": {
        #     "CLIENT_CLASS": "django_redis.client.DefaultClient",
        #     "CONNECTION_POOL_KWARGS": {"max_connections": 100}
        #     # "PASSWORD": "密码",
        # }
    }
}
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'utils.auth.LoginAuth',  # 自定义认证
    )
}
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# ############################# 阿里云短信配置 ##########################
ALIBABA_OSS_ACCESS_KEY_ID = "LTAI5tRGU75GhUVbKyrJVCxm"
ALIBABA_OSS_ACCESS_KEY_SECRET = "d1BragzkhOhThuqQDiccOFDV6KYrjX"
# ALIBABA_ACCESS_KEY_ID = "LTAI5tFMHAjH4tJzPkQwvmej"
# ALIBABA_ACCESS_KEY_SECRET = "3giwh4k4mdznc5jnM3AG2emVcfF3Q6"
ALIBABA_BUCKET_ENDPOINT = "oss-cn-beijing.aliyuncs.com"
ALIBABA_OSS_BUCKET_NAME = "2023-05-29-test"
ALIBABA_SMS_CONFIG = {
    # 您的AccessKey ID,
    "access_key_id": "LTAI5tBZP44V9193MEYBQ8kJ",
    # 您的AccessKey Secret,
    "access_key_secret": "pPnSgLTwPpldnnFIgXWAUcRVvcOzHR"
}
# ALIBABA_SMS_CONFIG.endpoint = 'dysmsapi.aliyuncs.com'
ALIBABA_SECURITYTOKEN = 'yourToken'
# ALIBABA_SMS_CONFIG = "AKIDW3Rgszw84ylQxMzNn7KOJ6kFPSL5c5MU"
# TENCENT_SECRET_KEY = "GQSMXmtsjR0QhuIalzTp250nU6digZSD"
# TENCENT_CITY = "ap-guangzhou"
# TENCENT_APP_ID = "1400302209"
# TENCENT_SIGN = "Python之路"
