# Generated by Django 4.2.1 on 2023-05-31 03:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackGround',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='backgrand/')),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontGround',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='frontground/')),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('language', models.CharField(choices=[('ZH', 'Chinese'), ('EN', 'English')], max_length=2)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='speakers/')),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pose', models.CharField(choices=[('half', '半身'), ('sitting', '坐姿'), ('full_sitting', '大半身'), ('full_body', '全身')], max_length=255)),
                ('default_pos', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='virtualperson/Images/')),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('video', models.FileField(upload_to='virtualperson/Videos/')),
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
